# Generated by Django 2.2.7 on 2019-11-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorname', models.CharField(max_length=100)),
                ('visitoremail', models.EmailField(max_length=140)),
                ('visitorphone', models.CharField(max_length=10)),
                ('hostname', models.CharField(max_length=100)),
                ('hostemail', models.EmailField(max_length=40)),
                ('hostphone', models.CharField(max_length=10)),
                ('visitorarrivaltime', models.TimeField(auto_now_add=True)),
                ('visitordeparturetime', models.TimeField(auto_now=True)),
                ('addressvisited', models.CharField(default='address1', max_length=100)),
                ('departed', models.BooleanField(default=False)),
            ],
        ),
    ]
