# Generated by Django 2.2.7 on 2019-12-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='addressvisited',
            field=models.CharField(default='The LNMIIT Institute Of Information Technology,Jaipur', max_length=100),
        ),
    ]
